// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: student/student.proto

package student

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Assignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Marks         int32                  `protobuf:"varint,2,opt,name=marks,proto3" json:"marks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_student_student_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_student_student_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_student_student_proto_rawDescGZIP(), []int{0}
}

func (x *Assignment) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Assignment) GetMarks() int32 {
	if x != nil {
		return x.Marks
	}
	return 0
}

type FinalGrade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Average       float32                `protobuf:"fixed32,1,opt,name=Average,proto3" json:"Average,omitempty"`
	Remarks       string                 `protobuf:"bytes,2,opt,name=Remarks,proto3" json:"Remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalGrade) Reset() {
	*x = FinalGrade{}
	mi := &file_student_student_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalGrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalGrade) ProtoMessage() {}

func (x *FinalGrade) ProtoReflect() protoreflect.Message {
	mi := &file_student_student_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalGrade.ProtoReflect.Descriptor instead.
func (*FinalGrade) Descriptor() ([]byte, []int) {
	return file_student_student_proto_rawDescGZIP(), []int{1}
}

func (x *FinalGrade) GetAverage() float32 {
	if x != nil {
		return x.Average
	}
	return 0
}

func (x *FinalGrade) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

var File_student_student_proto protoreflect.FileDescriptor

const file_student_student_proto_rawDesc = "" +
	"\n" +
	"\x15student/student.proto\x12\astudent\"8\n" +
	"\n" +
	"Assignment\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05marks\x18\x02 \x01(\x05R\x05marks\"@\n" +
	"\n" +
	"FinalGrade\x12\x18\n" +
	"\aAverage\x18\x01 \x01(\x02R\aAverage\x12\x18\n" +
	"\aRemarks\x18\x02 \x01(\tR\aRemarks2Q\n" +
	"\x0eStudentService\x12?\n" +
	"\x11SubmitAssignments\x12\x13.student.Assignment\x1a\x13.student.FinalGrade(\x01B\vZ\t./studentb\x06proto3"

var (
	file_student_student_proto_rawDescOnce sync.Once
	file_student_student_proto_rawDescData []byte
)

func file_student_student_proto_rawDescGZIP() []byte {
	file_student_student_proto_rawDescOnce.Do(func() {
		file_student_student_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_student_student_proto_rawDesc), len(file_student_student_proto_rawDesc)))
	})
	return file_student_student_proto_rawDescData
}

var file_student_student_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_student_student_proto_goTypes = []any{
	(*Assignment)(nil), // 0: student.Assignment
	(*FinalGrade)(nil), // 1: student.FinalGrade
}
var file_student_student_proto_depIdxs = []int32{
	0, // 0: student.StudentService.SubmitAssignments:input_type -> student.Assignment
	1, // 1: student.StudentService.SubmitAssignments:output_type -> student.FinalGrade
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_student_student_proto_init() }
func file_student_student_proto_init() {
	if File_student_student_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_student_student_proto_rawDesc), len(file_student_student_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_student_student_proto_goTypes,
		DependencyIndexes: file_student_student_proto_depIdxs,
		MessageInfos:      file_student_student_proto_msgTypes,
	}.Build()
	File_student_student_proto = out.File
	file_student_student_proto_goTypes = nil
	file_student_student_proto_depIdxs = nil
}
